
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class frmMain extends javax.swing.JFrame {

    int jam;
    int menit;
    int detik;
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        
        setTanggal() ;
        setJam() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Save1 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        print = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        No = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Makanan = new javax.swing.JComboBox();
        Mkn = new javax.swing.JTextField();
        Mknttl = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        Minuman = new javax.swing.JComboBox();
        Mnmttl = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Mnm = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kasir = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 153, 51));
        jPanel8.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Pemesan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(null);

        Hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No_Pemesan", "Nama", "Makanan", "Minuman", "Total"
            }
        ));
        Hasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 960, 240);

        jPanel8.add(jPanel1);
        jPanel1.setBounds(10, 340, 980, 270);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dll"));
        jPanel5.setLayout(null);

        Save1.setText("SAVE");
        Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save1ActionPerformed(evt);
            }
        });
        jPanel5.add(Save1);
        Save1.setBounds(40, 40, 90, 30);

        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel5.add(Clear);
        Clear.setBounds(150, 40, 90, 30);

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel5.add(refresh);
        refresh.setBounds(150, 90, 90, 30);

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel5.add(Delete);
        Delete.setBounds(40, 90, 90, 30);

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel5.add(print);
        print.setBounds(40, 140, 90, 30);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit);
        exit.setBounds(150, 140, 90, 30);

        jPanel8.add(jPanel5);
        jPanel5.setBounds(690, 90, 300, 240);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(null);

        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        jPanel3.add(No);
        No.setBounds(20, 40, 130, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("No.Pemesan");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 20, 130, 20);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel3.add(Nama);
        Nama.setBounds(20, 100, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nama Pemesan");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 80, 130, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Makanan ");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(20, 140, 130, 20);

        Makanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Makanan--", "Ayam Goreng", "Bebek Goreng", "Lele Goreng", "Udang Goreng" }));
        jPanel3.add(Makanan);
        Makanan.setBounds(20, 160, 130, 30);

        Mkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MknActionPerformed(evt);
            }
        });
        jPanel3.add(Mkn);
        Mkn.setBounds(20, 200, 130, 30);

        Mknttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MknttlActionPerformed(evt);
            }
        });
        jPanel3.add(Mknttl);
        Mknttl.setBounds(160, 160, 30, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Minuman ");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(200, 20, 130, 20);

        Minuman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Minuman--", "Es Teh", "Air Mineral", "Es Jeruk" }));
        Minuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinumanActionPerformed(evt);
            }
        });
        jPanel3.add(Minuman);
        Minuman.setBounds(200, 40, 130, 30);

        Mnmttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnmttlActionPerformed(evt);
            }
        });
        jPanel3.add(Mnmttl);
        Mnmttl.setBounds(340, 40, 30, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Total");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(200, 110, 130, 20);
        jPanel3.add(Mnm);
        Mnm.setBounds(200, 80, 130, 30);

        Total.setEditable(false);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        jPanel3.add(Total);
        Total.setBounds(200, 130, 130, 30);

        total.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        total.setText("TOTAL");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel3.add(total);
        total.setBounds(230, 190, 90, 30);

        jPanel8.add(jPanel3);
        jPanel3.setBounds(280, 90, 400, 240);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel14.setText("- Jus Jeruk");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 190, 100, 14);

        jLabel13.setText("- Air Mineral");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(20, 170, 100, 14);

        jLabel12.setText("- Es Teh");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(20, 150, 110, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Minuman");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 120, 80, 30);

        jLabel7.setText("- Bebek Goreng ");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 110, 110, 14);

        jLabel6.setText("- Lele Goreng ");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 90, 100, 14);

        jLabel5.setText("- Ayam Goreng ");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 70, 100, 14);

        jLabel4.setText("- Udang Goreng ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 50, 110, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Makanan");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 20, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Harga");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(170, 20, 80, 30);

        jLabel19.setText("Rp 20.000");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(170, 50, 90, 14);

        jLabel17.setText("Rp 15.000");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(170, 70, 100, 14);

        jLabel20.setText("Rp 13.000");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(170, 90, 100, 14);

        jLabel21.setText("Rp 20.000");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(170, 110, 110, 14);

        jLabel22.setText("Rp 5.000");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(170, 150, 90, 14);

        jLabel18.setText("Rp 4.000");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(170, 170, 100, 14);

        jLabel23.setText("Rp 6.000");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(170, 190, 70, 14);

        jPanel8.add(jPanel4);
        jPanel4.setBounds(10, 90, 260, 240);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(null);

        kasir.setText("Miftah");
        jPanel2.add(kasir);
        kasir.setBounds(650, 20, 80, 30);

        tanggal.setText("Tanggal");
        jPanel2.add(tanggal);
        tanggal.setBounds(740, 0, 190, 30);

        waktu.setText("Waktu");
        jPanel2.add(waktu);
        waktu.setBounds(740, 30, 190, 30);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("KEDAI MJ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 0, 310, 70);

        jPanel6.setLayout(null);
        jPanel2.add(jPanel6);
        jPanel6.setBounds(-10, -10, 0, 0);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(null);
        jPanel2.add(jPanel7);
        jPanel7.setBounds(-10, -20, 0, 0);

        jPanel8.add(jPanel2);
        jPanel2.setBounds(10, 10, 980, 70);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 0, 1000, 620);

        setSize(new java.awt.Dimension(1016, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HasilMouseClicked
        // TODO add your handling code here:
        int baris = Hasil.getSelectedRow();
        if(baris != -1){
            No.setText(Hasil.getValueAt(baris, 0).toString());
            Nama.setText(Hasil.getValueAt(baris, 1).toString());
            if("Ayam Goreng".equals(Hasil.getValueAt(baris, 2).toString())){
                Makanan.getSelectedItem();
            }else if("Bebek Goreng".equals(Hasil.getValueAt(baris, 2).toString())){
                Makanan.getSelectedItem();
            }else if("Lele Goreng".equals(Hasil.getValueAt(baris, 2).toString())){
                Makanan.getSelectedItem();
            }else if("Udang Goreng".equals(Hasil.getValueAt(baris, 2).toString())){
                Makanan.getSelectedItem();
            }else if("Bebek Goreng".equals(Hasil.getValueAt(baris, 2).toString())){
                Makanan.getSelectedItem();
            }

            if("Es Teh".equals(Hasil.getValueAt(baris, 3).toString())){
                Minuman.getSelectedItem();
            }else if("Air Mineral".equals(Hasil.getValueAt(baris, 3).toString())){
                Minuman.getSelectedItem();
            }else if("Es Jeruk".equals(Hasil.getValueAt(baris, 3).toString())){
                Minuman.getSelectedItem();
            }

            Total.setText(Hasil.getValueAt(baris, 1).toString());

        }
    }//GEN-LAST:event_HasilMouseClicked

    private void Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save1ActionPerformed
        
            String makan = Makanan.getSelectedItem().toString();
            String minum = Minuman.getSelectedItem().toString();

            if (Makanan.getSelectedItem() == "Ayam Goreng"){
            }if (Makanan.getSelectedItem() == "Bebek Goreng"){
            }if (Makanan.getSelectedItem() == "Lele Goreng"){
            }if (Makanan.getSelectedItem() == "Udang Goreng"){          
            };

            if (Minuman.getSelectedItem() == "Es Teh"){
            }if (Minuman.getSelectedItem() == "Air Mineral"){
            }if (Minuman.getSelectedItem() == "Es Jeruk"){
            };

            String SQL = "INSERT INTO `t_transaksi`(`NOP`, `nama`, `makanan`, `minuman`, `total`)"
            + "VALUES('"+No.getText()+"','"+Nama.getText()+"','"+makan+"','"
            +minum+"','"+Total.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil DItambah", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambah", "Sukses", JOptionPane.WARNING_MESSAGE);
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_Save1ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Nama.setText("");
        No.setText("");
        Makanan.getSelectedItem();
        Minuman.getSelectedItem();
        Mkn.setText("");
        Mnm.setText("");
        Mknttl.setText("");
        Mnmttl.setText("");
        Total.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int baris = Hasil.getSelectedRow();
        if(baris != -1){
            String No_pemesan = Hasil.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_transaksi WHERE NOP ='"+No_pemesan+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("Pesanan KEDAI MJ");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)   ");

        try {
            Hasil.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void MknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MknActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MknActionPerformed

    private void MknttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MknttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MknttlActionPerformed

    private void MinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinumanActionPerformed

    private void MnmttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnmttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnmttlActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        if("".equals(No.getText()) || "".equals(Nama.getText()) || "".equals(Makanan.getSelectedItem())
                || "".equals(Mkn.getText()) || "".equals(Mnm.getText()) || "".equals(Mknttl.getText())
                || "".equals(Mnmttl.getText()) || "".equals(Minuman.getSelectedItem()) || "".equals(Total.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {

        int hrgmkn = Integer.parseInt(String.valueOf(Mkn.getText()));
        int hrgmnm = Integer.parseInt(String.valueOf(Mnm.getText()));
        int tlmkn = Integer.parseInt(String.valueOf(Mknttl.getText()));
        int tlmnm = Integer.parseInt(String.valueOf(Mnmttl.getText()));
        Total.setText(String.valueOf(total));

        int ttlmkn = hrgmkn*tlmkn;
        int ttlmnm = hrgmnm*tlmnm;
        int ttl = ttlmkn+ttlmnm;
        int ttld = ttl;
        if(ttl > 200000){
            ttld = ttl * 90/100;
            JOptionPane.showMessageDialog(this,"Anda mendapatkan diskon sebesar 10% ( Rp "+ttl*10/100+" )\n"
                    + "dari "+ttl+" menjadi Rp "+ttl * 90/100);
        }
        
        Total.setText(String.valueOf(ttld));}
    }//GEN-LAST:event_totalActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTable Hasil;
    private javax.swing.JComboBox Makanan;
    private javax.swing.JComboBox Minuman;
    private javax.swing.JTextField Mkn;
    private javax.swing.JTextField Mknttl;
    private javax.swing.JTextField Mnm;
    private javax.swing.JTextField Mnmttl;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField No;
    private javax.swing.JButton Save1;
    private javax.swing.JTextField Total;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kasir;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel tanggal;
    private javax.swing.JButton total;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NOP","nama","makanan","minuman","total"};
        DefaultTableModel dtm  = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try {
            while (rs.next()) {
                String NOP = rs.getString(1);
                String nama= rs.getString(2);
                String makanan = rs.getString(3);
                String minuman = rs.getString(4);
                String total = rs.getString(5);
                String data[] = {NOP,nama,makanan,minuman,total};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        Hasil.setModel(dtm);
    }

    private void setTanggal() {
        java.util.Date skrg = new java.util.Date() ;
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy") ;
        tanggal.setText(kal.format(skrg));
    }

    private void setJam() {
        ActionListener taskPerformer = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
            
                Date dt = new Date() ;
                int nilai_jam = dt.getHours() ;
                int nilai_menit = dt.getMinutes() ;
                int nilai_detik = dt.getSeconds() ;
                if(nilai_jam <= 9){
                    
                 jam = 0 ;   
                    
                } if(nilai_menit <= 9){
                    
                 menit = 0 ;   
                    
                } if(nilai_jam <= 9){
                    
                 detik = 0 ;   
                    
                }
                String Jam = jam + Integer.toString(nilai_jam) ;
                String Menit = menit + Integer.toString(nilai_menit) ;
                String Detik = detik + Integer.toString(nilai_detik) ;
                
                waktu.setText("Jam " + Jam + ":" + Menit + ":" + Detik );
            }
            
        };
        
            new Timer(100, taskPerformer).start() ;
        }
}
